version: '2.4'

services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 80:80
    # devices:
    #  - /dev/ttyACM0:/dev/ttyACM0
    #  - /dev/video0:/dev/video0
    volumes:
     - octoprint:/octoprint
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    #environment:
    #  - ENABLE_MJPG_STREAMER=true
  
  streamer1:
    build: .
    ports:
      - 8001:8080
    devices:
      - /dev/video0:/dev/video0
    environment:
      - MJPG_RES=640x480
      - MJPG_FPS=25
      - MJPG_USER=admin
      - MJPG_PASS=adm1n
    restart: always

  streamer2:
    build: .
    ports:
      - 8002:8080
    devices:
      - /dev/video1:/dev/video0
    environment:
      - MJPG_RES=640x480
      - MJPG_FPS=25
      - MJPG_USER=admin
      - MJPG_PASS=adm1n
    restart: always
  
  ####
  # uncomment if you wish to edit the configuration files of octoprint
  # refer to docs on configuration editing for more information
  ####

  config-editor:
   image: linuxserver/code-server
   ports:
     - 8443:8443
   depends_on:
     - octoprint
   restart: unless-stopped
   environment:
     - PUID=0
     - GUID=0
     - TZ=America/Chicago
   volumes:
     - octoprint:/octoprint

volumes:
  octoprint: